### ISSUE TITLE
Arm Cortex-M3 

### ISSUE THREAD

**Issue by LETARTARE** [gnea/gnea#2]
Hello,
I found on Ebay basic Cortex card [Stm32f103c8t6 Cortex-M3 ](http://www.ebay.com/itm/252832184945?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT) associated [St-Link V2](http://www.ebay.com/itm/252782090497?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT)
Could you if the future version of Gnea could work with ?
Good night.

**Comment by chamnit** [comment]
@LETARTARE : Can't see why not. I've been building a HAL interface that will allow porting to most controllers quickly and easily. It'll just take someone willing to do the port. I'll be maintaining the main HAL and the SAMD21 port.

**Comment by Harvie** [comment]
See #4
